services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
