services:
    todo-backend:
        build: .
        image: todo-backend
        environment:
            - REDIS_URL=redis://localhost:7890
            - MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database
        ports:
            - '3001:3000'
