DELETE http://localhost:3001/api/blogs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InRlc3RAZ21haWwuY29tIiwibmFtZSI6IlRlc3R5IiwiY3JlYXRlZEF0IjoiMjAyMy0xMC0wMVQxMDowOToxMC4wMTdaIiwidXBkYXRlZEF0IjoiMjAyMy0xMC0wMVQxMDowOToxMC4wMTdaIn0sImlhdCI6MTY5NjE1NDk1Nn0.00JwcRIlYS2G5uIi3y_nFINMQoVwFeH07CtUNiOp43U
