POST http://127.0.0.1:3003/api/blogs
Content-Type: application/json

{
    "title": "A cool blog",
    "author": "Ian de Jesus",
    "url": "https://google.com",
    "likes": 123
}

### Example 2
POST http://127.0.0.1:3003/api/blogs
Content-Type: application/json

{
    "title": "Another blog",
    "author": "Jan de Jesus",
    "url": "https://spotify.com",
    "likes": 321
}